export const gradeValues = [
  { value: "5a", label: "5a" },
  { value: "5a+", label: "5a+" },
  { value: "5b", label: "5b" },
  { value: "5b+", label: "5b+" },
  { value: "5c", label: "5c" },
  { value: "5c+", label: "5c+" },
  { value: "6a", label: "6a" },
  { value: "6a+", label: "6a+" },
  { value: "6b", label: "6b" },
  { value: "6b+", label: "6b+" },
  { value: "6c", label: "6c" },
  { value: "6c+", label: "6c+" },
  { value: "7a", label: "7a" },
  { value: "7a+", label: "7a+" },
  { value: "7b", label: "7b" },
  { value: "7b+", label: "7b+" },
  { value: "7c", label: "7c" },
  { value: "7c+", label: "7c+" },
  { value: "8a", label: "8a" },
];
