export const numericGrades = [
  { value: "5a", label: "5a" },
  { value: "5a+", label: "5a+" },
  { value: "5b", label: "5b" },
  { value: "5b+", label: "5b+" },
  { value: "5c", label: "5c" },
  { value: "5c+", label: "5c+" },
  { value: "6a", label: "6a" },
  { value: "6a+", label: "6a+" },
  { value: "6b", label: "6b" },
  { value: "6b+", label: "6b+" },
  { value: "6c", label: "6c" },
  { value: "6c+", label: "6c+" },
  { value: "7a", label: "7a" },
  { value: "7a+", label: "7a+" },
  { value: "7b", label: "7b" },
  { value: "7b+", label: "7b+" },
  { value: "7c", label: "7c" },
  { value: "7c+", label: "7c+" },
  { value: "8a", label: "8a" },
];

// export const numericGrades = [
//   { value: [48, 49], label: "5a" },
//   { value: [50, 51], label: "5a+" },
//   { value: [52, 53], label: "5b" },
//   { value: [54, 55], label: "5b+" },
//   { value: [56, 57], label: "5c" },
//   { value: [58, 59], label: "5c+" },
//   { value: [60, 61], label: "6a" },
//   { value: [62, 63], label: "6a+" },
//   { value: [64, 65], label: "6b" },
//   { value: [66, 67], label: "6b+" },
//   { value: [68, 69], label: "6c" },
//   { value: [70, 71], label: "6c+" },
//   { value: [72, 73], label: "7a" },
//   { value: [74, 75], label: "7a+" },
//   { value: [76, 77], label: "7b" },
//   { value: [78, 79], label: "7b+" },
//   { value: [80, 81], label: "7c" },
//   { value: [82, 83], label: "7c+" },
//   { value: [84, 85], label: "8a" },
// ];
